services:
  node:
    image: node:9
    working_dir: /app
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    command: >
      sh -c "npm install
      && npm run build
      && npm run start"
    environment:
      TELEGRAM_TOKEN: 7033070973:AAHfqTUwvro2sSabR2Hvjh-Xrqlt56XpUMY
  nginx:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - 8080:80
